### ISSUE TITLE
Error unmapped packet S_Fishing_Bite

### ISSUE THREAD

**Issue by Gazeciara** [SoliaRdi/auto-fishing#12]
Hi! I'm new with proxy, tried to run auto fishing and that's what I've got. I did everything what was said in Readme. I don't know what else can I do

Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:231:23)
    at Dispatch.hook (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:310:21)
    at Module.hook (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at new autoFishing (D:\CaaliTeraProxy\mods\auto-fishing-master\index.js:35:6)
    at ModuleManager.load (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:138:35)
    at installedModules.forEach.mod (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45)
    at Dispatch.emit (events.js:189:13)

**Comment by Gazeciara** [comment]
Thank you, it worked :)
