### ISSUE TITLE
Any way around this?

### ISSUE THREAD

**Issue by ChicknWing** [SoliaRdi/auto-fishing#13]
[mods] ERROR: Module "auto-fishing" could not be loaded!
[mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
Error: Forbidden module behavior.
    at ModuleManager.load (C:\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:146:27)
    at installedModules.forEach.mod (C:\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (C:\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (C:\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45)
    at Dispatch.emit (events.js:182:13)
    at Dispatch.setProtocolVersion (C:\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:436:9)
    at Dispatch.handle (C:\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:455:11)
    at Socket.RealClient.socket.on (C:\tera-proxy\node_modules\tera-proxy-game\lib\clients\RealClient.js:38:31)
    at Socket.emit (events.js:182:13)

**Comment by SoliaRdi** [comment]
update in a few minutes
