### ISSUE TITLE
NPC reconition

### ISSUE THREAD

**Issue by cybrwolf** [SoliaRdi/auto-fishing#132]
Hey, so far work perfectly in Seren's fishery

but dosent reconize Tanysilain and Bridier npc in Vexatus (NA, if that matter) keep saying Warning, no seller npc at acceptable range, even when closer to 6m reange

**Comment by chingchongbing123** [comment]
@SoliaRdi Do I have to do anything special to make it work? I just downloaded the auto fisher proxy then typed it near the npc but it doesn't work but the filet mode works but not sell to npc.

**Comment by cybrwolf** [comment]
@SoliaRdi if you need more testing, or debugging, lets me know, ill supply any requested information (and all my opcodes are up to date since everyting work fine in seren's)

**Comment by chingchongbing123** [comment]
@cybrwolf Hey, how did you make it work in Seren's fishery? Mine still says No seller npc at acceptable range :(

**Comment by chingchongbing123** [comment]
@cybrwolf This is what I get when I did your thing.
 TypeError: Cannot read property 'contractId' of undefined
    at mod.setTimeout (C:\Users\DR\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:284:42)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\DR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:279:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

**Comment by cybrwolf** [comment]
my thing as you said.. its the config file for Charactername.json file when you do fish save

**Comment by SoliaRdi** [comment]
Try in few minutes

**Comment by chingchongbing123** [comment]
> Try in few minutes

what is the difference now? Thank you!

**Comment by SoliaRdi** [comment]
?_?
This I want from you to know if there is a difference

**Comment by chingchongbing123** [comment]
> ?_?
> This I want from you to know if there is a difference

Just tried it but I get this error:
TypeError: Cannot read property 'gameId' of undefined
    at mod.setTimeout (C:\Users\DR\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:775:35)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\DR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:279:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

No idea what it is :(

**Comment by SoliaRdi** [comment]
Oh, damn. My mistake

**Comment by SoliaRdi** [comment]
Should be fine now =_=

**Comment by chingchongbing123** [comment]
@SoliaRdi 
It worked three times and it disconnected me. I think it's just my client though I don't think it breaks for anybody else.
TypeError: Cannot read property 'contractId' of undefined
    at mod.setTimeout (C:\Users\DR\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:284:42)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\DR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:279:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

**Comment by cybrwolf** [comment]
Working flawlessly ! thanks @SoliaRdi i appreciate your work

**Comment by SoliaRdi** [comment]
@chingchongbing123 you can try without other modules, dk why this can happen

**Comment by cybrwolf** [comment]
@chingchongbing123  also try updating with the new version.. should work
