### ISSUE TITLE
unmapped packet "S_PCBANGINVENTORY_DATALIST" ????

### ISSUE THREAD

**Issue by trev44** [SoliaRdi/auto-fishing#174]

**Comment by trev44** [comment]
ERROR: Module "Auto-Fishing" (auto-fishing) could not be loaded!

**Comment by flytomoon88** [comment]
i also want to know which action will trigger this so that i can find and map for SEA. thanks!

**Comment by etora13** [comment]
still waiting for a fix, it happen to me today in SEA

**Comment by kath19x** [comment]
Same here. It was working until today in SEA, getting the same error

**Comment by AngelOfTheNight** [comment]
This is what i get,

[18:28:18.150] Error: [dispatch] hook: unmapped packet "S_PCBANGINVENTORY_DATALIST"
    at Dispatch.createHook (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:257:23)
    at Dispatch.hook (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:318:27)
    at Module.hook (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:88:32)
    at new autoFishing (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:476:6)
    at ModuleManager.load (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:154:35)
    at C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:118:31)
    at Socket.<anonymous> (C:\Users\[Name]\AppData\Local\Programs\CaaliTeraProxy\bin\connectionManager.js:63:47)
    at Socket.emit (events.js:199:15)

**Comment by LxMk864** [comment]
"S_PCBANGINVENTORY_DATALIST"
Eu same error and ingame command "start" not find

**Comment by SoliaRdi** [comment]
i'll update soon, busy atm

**Comment by LxMk864** [comment]
Oh great

**Comment by andersonepk** [comment]
Can update opcodes to NA too?
Would be great thanks

**Comment by Distortionn** [comment]
Packet should be premium_slot now afaik.

This as well yeah:

```
Error: [dispatch] hook: unmapped packet "S_PCBANGINVENTORY_DATALIST"
    at Dispatch.createHook (C:\Users\xxx\Desktop\TERA\caali\Proxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:257:23)
    at Dispatch.hook (C:\Users\xxx\Desktop\TERA\caali\Proxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:318:27)
    at Module.hook (C:\Users\xxx\Desktop\TERA\caali\Proxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:88:32)
    at new autoFishing (C:\Users\xxx\Desktop\TERA\caali\Proxy\mods\auto-fishing\index.js:476:6)
    at ModuleManager.load (C:\Users\xxx\Desktop\TERA\caali\Proxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:154:35)
    at C:\Users\xxx\Desktop\TERA\caali\Proxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\xxx\Desktop\TERA\caali\Proxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:118:31)
    at Socket.<anonymous> (C:\Users\xxx\Desktop\TERA\caali\Proxy\bin\connectionManager.js:63:47)
    at Socket.emit (events.js:199:15)
```

**Comment by SoliaRdi** [comment]
fixed
