### ISSUE TITLE
error

### ISSUE THREAD

**Issue by chacha080** [SoliaRdi/auto-fishing#19]
Error S_Fishing_bite

[mods] ERROR: Module "auto-fishing" could not be loaded!
[mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:231:23)
    at Dispatch.hook (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:310:21)
    at Module.hook (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at new autoFishing (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:31:6)
    at ModuleManager.load (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:149:35)
    at installedModules.forEach.mod (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (C:\Users\TOR\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45)
    at Dispatch.emit (events.js:189:13)

**Comment by SoliaRdi** [comment]
region?

**Comment by SoliaRdi** [comment]
download sea opcodes
