### ISSUE TITLE
i got bait error

### ISSUE THREAD

**Issue by LReaper2019** [SoliaRdi/auto-fishing#198]
[23:22:36.916] [command] ERROR: Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\-\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\-\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:298:27)
    at Module.hook (C:\Users\-\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Users\-\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Users\-\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Users\-\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1127:6)
    at CommandBase.exec (C:\Users\-\AppData\Local\Programs\TeraToolbox\mods\command\index.js:195:16)
    at hookCommand (C:\Users\-\AppData\Local\Programs\TeraToolbox\mods\command\index.js:70:31)
    at Object.callback (C:\Users\-\AppData\Local\Programs\TeraToolbox\mods\command\index.js:80:29)
    at Dispatch.handle (C:\Users\-\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:439:45)

**Comment by LReaper2019** [comment]
after update then i got this

**Comment by SoliaRdi** [comment]
typing your region would be more useful than traditional "no needed opcodes error"

**Comment by LReaper2019** [comment]
can giv me etc ?

**Comment by LReaper2019** [comment]
i from sea

**Comment by LReaper2019** [comment]
but i dun why my fish didnt auto catch even i put the change the code

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/61552113-9cc0b200-aa5f-11e9-99f0-21fddfa7cf12.png)

**Comment by LReaper2019** [comment]
protocol.353339.map
C_END_FISHING_MINIGAME = 45189
C_MEDAL_STORE_BUY_ADD_BASKET = 34609
C_MEDAL_STORE_COMMIT = 59361
C_PUT_WARE_ITEM = 27874
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 58231
C_START_FISHING_MINIGAME = 44548
C_STORE_COMMIT = 33352
C_STORE_SELL_ADD_BASKET = 63003
S_FISHING_BITE = 64034
S_FISHING_CATCH = 30497
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 40046
S_START_FISHING_MINIGAME = 47473
S_STORE_BASKET = 63409
this is my sea server it work but it didnt catch fish after manual it will retry but still no catch fish

**Comment by LReaper2019** [comment]
i havent get the store and other i juz change the code fishing

**Comment by SoliaRdi** [comment]
check your opcodes with this ;)
