### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by Frostwaffles** [SoliaRdi/auto-fishing#212]
when i type " fish " on proxy chat it says ;
Auto fishing activated. Manually start fishing now.
and 2 seconds later,
Error running callback for command " fish "

**Comment by SoliaRdi** [comment]
i'm not extrasense, give error log

**Comment by Frostwaffles** [comment]
where can i get that error log?

**Comment by SoliaRdi** [comment]
in console

**Comment by Frostwaffles** [comment]
what console? i have proxy chat in game , you mean there? what should i type to see it?

**Comment by Frostwaffles** [comment]
[12:38:07.722] [mods] ERROR: Module "easy-fishing" could not be loaded!
[12:38:07.723] [mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
[12:38:07.725] Error: [dispatch] [easy-fishing] hook: Error: version 10 of message (name: "S_LOGIN", code: 35367) is outdated and cannot be used anymore
    at Dispatch.createHook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:248:27)
    at Dispatch.hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at new EasyFishing (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\easy-fishing-master\index.js:20:9)
    at ModuleManager.load (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)
[12:38:07.752] [mods] Loaded module "FPS-UTILS" (fps-utils)
[12:38:07.758] [mods] Loaded module "InstantEverything" (instant-everything)
[12:38:07.917] [mods] Loaded module "PSP" (skill-prediction)
[12:39:11.429] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1127:6)
    at CommandBase.exec (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\command\index.js:195:16)
    at hookCommand (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\command\index.js:70:31)
    at Object.callback (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\command\index.js:80:29)
    at Dispatch.handle (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

**Comment by SoliaRdi** [comment]
I dont think this is my module

**Comment by Frostwaffles** [comment]
i am pretty sure i installed it from the zip in this post but let me reinstall it.

**Comment by SoliaRdi** [comment]
dont forget opcodes. About not mine: easy-fishing!=auto-fishing, i have correct support link to repo, i dont use S_LOGIN
