### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by Frostwaffles** [SoliaRdi/auto-fishing#213]
I dont want to be rude or anything like that. Please dont get me wrong. I have sent you wrong log that i had 2 plugins for fishing installed. I deleted the one not yours and sorry for wasting your time. Here is the error log you requested.

[12:50:23.593] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1127:6)
    at CommandBase.exec (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\command\index.js:195:16)
    at hookCommand (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\command\index.js:70:31)
    at Object.callback (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\mods\command\index.js:80:29)
    at Dispatch.handle (C:\Users\muco2\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

**Comment by SoliaRdi** [comment]
install opcodes

**Comment by Frostwaffles** [comment]
ohh , how can i do it?

**Comment by SoliaRdi** [comment]
https://github.com/SoliaRdi/auto-fishing/blob/master/README.MD

**Comment by Frostwaffles** [comment]
i am playing in NA server do i need to install all those NA named protocols? or last one is enough?

**Comment by SoliaRdi** [comment]
only current version

**Comment by Frostwaffles** [comment]
If i open notepad and write those codes in the opcodes and save them as .map extension. And install them in my proxy. Does that mean i installed opcodes?

**Comment by SoliaRdi** [comment]
yes, if folders is correct, like in readme. You can move file or merge content, it doesn't matter

**Comment by Frostwaffles** [comment]
thank you
