### ISSUE TITLE
Error code since last patch

### ISSUE THREAD

**Issue by Nykkyta** [SoliaRdi/auto-fishing#232]
Hello,
Since today's patch, when I try to initiate the module, I get the following error messages;
When starting the game: " [Auto-fishing] C_PUT_WARE_ITEM not mapped, banker functions will be disabled"
When starting module with /8 FISH: "Error running callback for command "fish"

In the TERA toolbox, i get this red message;
[19:17:19.496] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Games\TeraToolbox\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Games\TeraToolbox\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Games\TeraToolbox\mods\auto-fishing-master\index.js:1137:6)
    at CommandBase.exec (C:\Games\TeraToolbox\mods\command\index.js:195:16)
    at hookCommand (C:\Games\TeraToolbox\mods\command\index.js:70:31)
    at Object.callback (C:\Games\TeraToolbox\mods\command\index.js:80:29)
    at Dispatch.handle (C:\Games\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

**Comment by Nykkyta** [comment]
Solved with new EU map

thx

**Comment by Nykkyta** [comment]
Hello,

the issue is back, since last patch(5/09). When activating the module (/8 fish) i get the message
_[Auto-fishing] Autofishing activated. Manually start fishing now. 
[Toolbox Error running callback for command "fish"_
And the module is not working...

Thx for your help

**Comment by SoliaRdi** [comment]
reason probably same as before

**Comment by Savateria** [comment]
After I edited the protocol.351828.map (EU 85.07) it works fine again

**Comment by XelZero** [comment]
opcodes for NA are alos broken - im getting the same error and cant find them - im not good with the locating of them by using a mod to get from game and i havent been able to find anyone who has them listed

**Comment by Peckspas** [comment]
EU also broken with error unmapped packet "s_fishing_bite"

**Comment by SoliaRdi** [comment]
Update opcodes|defs. Opcodes in repo only for ru rn

**Comment by Kamoa** [comment]
most of NA

C_END_FISHING_MINIGAME = 54680
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 60856
C_START_FISHING_MINIGAME = 31241
C_STORE_COMMIT = 50506
C_STORE_SELL_ADD_BASKET = 62760
S_FISHING_BITE = 29161
S_FISHING_CATCH = 26933
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 54773
S_START_FISHING_MINIGAME = 42121
C_PUT_WARE_ITEM = 53587
S_STORE_BASKET =

**Comment by XelZero** [comment]
any luck on NA opcodes?

**Comment by SoliaRdi** [comment]
Na opcodes same as eu
