### ISSUE TITLE
No definition for packet error

### ISSUE THREAD

**Issue by TeraPlayer** [SoliaRdi/auto-fishing#240]
[16:53:13.395] [command] ERROR: Error: [dispatch] [auto-fishing] hook: Error: no definition found for message (name: "S_FISHING_BITE", code: 33459, version: 1)
    at Dispatch.createHook (E:\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:248:27)
    at Dispatch.hook (E:\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (E:\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (E:\CaaliTeraProxy\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (E:\CaaliTeraProxy\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (E:\CaaliTeraProxy\mods\auto-fishing-master\index.js:1137:6)
    at CommandBase.exec (E:\CaaliTeraProxy\mods\command\index.js:196:16)
    at hookCommand (E:\CaaliTeraProxy\mods\command\index.js:71:31)
    at Object.callback (E:\CaaliTeraProxy\mods\command\index.js:81:29)
    at Dispatch.handle (E:\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

What's this error about? ._.

**Comment by SoliaRdi** [comment]
About no definition found tbh

**Comment by TeraPlayer** [comment]
> About no definition found tbh

Erm how to fix it then >.>

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/64128366-e15d9e00-cdbe-11e9-90c9-638927892625.png)
