### ISSUE TITLE
fish not work tera eu

### ISSUE THREAD

**Issue by kosarvedi** [SoliaRdi/auto-fishing#244]
not work

**Comment by SoliaRdi** [comment]
Why you screenshot this but not console where any info about error can be found?

**Comment by SoliaRdi** [comment]
Probably opcodes was changed. I dont have them yet, pinkie probably too

**Comment by kosarvedi** [comment]
15:30:19.293] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1137:6)
    at CommandBase.exec (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\kosar\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

**Comment by SoliaRdi** [comment]
https://github.com/tera-proxy/tera-data/commit/106054bfcd14c9e2368f292ca514b22be9224dd1
