### ISSUE TITLE
Today No work

### ISSUE THREAD

**Issue by Fujikominee** [SoliaRdi/auto-fishing#245]
Fishing no work
[17:27:23.729] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\XXX\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook 
(C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:1137:6)
    at CommandBase.exec (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:196:16)
    at hookCommand (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:71:31)
    at Object.callback (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\xxx\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

**Comment by SoliaRdi** [comment]
update opcodes from pinkie

**Comment by Fujikominee** [comment]
I tried to do it, but I didn't understand the procedure well, so I get a command error ... but will you upgrade? <3

**Comment by wdprez** [comment]
I also got an issue. I don't get any error but the module doesn't do anything. When I get a fish, it just doesn't react to it. I did update my opcodes. Any idea what could be the cause?

**Comment by Fujikominee** [comment]
I don't know how to help you I'm in your same situation, to me by mistake, before the mini patch this morning everything was going perfectly, now it doesn't work, FACEPALM!

**Comment by wdprez** [comment]
Nvm I fixed it, I indeed did something wrong while updating my opcodes.

**Comment by Fujikominee** [comment]
he told me to update the files from pnki, but I didn't understand what I have to do and from this afternoon I try, I don't know how to do it, or at least I didn't understand what files to put and where to download them

**Comment by Bry0** [comment]
> he told me to update the files from pnki, but I didn't understand what I have to do and from this afternoon I try, I don't know how to do it, or at least I didn't understand what files to put and where to download them,I use TERA ToolBox Proxy, do you too?

-Update every opcode inside one of the .map files you downloaded for autofisher
-Rename the .map file to protocol.351828.map
-Replace the one in tera-data\map

**Comment by Fujikominee** [comment]
> > he told me to update the files from pnki, but I didn't understand what I have to do and from this afternoon I try, I don't know how to do it, or at least I didn't understand what files to put and where to download them,I use TERA ToolBox Proxy, do you too?
> 
> -Update every opcode inside one of the .map files you downloaded for autofisher
> -Rename the .map file to protocol.351828.map
> -Replace the one in tera-data\map

but those downloaded from here, or those downloaded from pinky (but I don't know what they are)? and where I excuse ignorance <3

**Comment by SoliaRdi** [comment]
Repo has opcodes only for ru region rn

**Comment by SoliaRdi** [comment]
other here 
![image](https://user-images.githubusercontent.com/34610562/64379435-90a4aa00-d037-11e9-93a8-39461196f8f4.png)

**Comment by Fujikominee** [comment]
> altro qui
> ![Immagine](https://user-images.githubusercontent.com/34610562/64379435-90a4aa00-d037-11e9-93a8-39461196f8f4.png)

so here I have to copy the files to the folder?

**Comment by SoliaRdi** [comment]
You can do this only for your current protocol version

**Comment by Fujikominee** [comment]
[23:08:37.954] [mods] ERROR: Module "Auto-Fishing" (auto-fishing) could not be loaded!
[23:08:37.954] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
[23:08:37.955] TypeError: moduleConstructor is not a constructor
    at ModuleManager.load (C:\Users\xxx\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\xxx\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\xxx\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\xxx\AppData\Local\Programs\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1047:10)


Thanks for the answers, but I didn't understand what I have to do, I don't have a clear explanation, I apologize but I'm not able, thanks for the answer, I give up .... <3

**Comment by SoliaRdi** [comment]
idk now what you done

**Comment by SoliaRdi** [comment]
you need simply download 1 file and replace it in Proxy-Folder/node_modules/tera-data/map

**Comment by Fujikominee** [comment]
> devi semplicemente scaricare 1 file e sostituirlo in Proxy-Folder / node_modules / tera-data / map

protocol.351828.map this?

**Comment by SoliaRdi** [comment]
Maybe, read your version in console or what Bry0 write above

**Comment by Fujikominee** [comment]
YYYhhhaaaayyyyy I succeeded thanks to all of you, with a little delay, but now it works thanks BRY0 and SoliaRDI.I followed Bry0's advice,mu@k <3
