### ISSUE TITLE
Cannot find module 'moment'

### ISSUE THREAD

**Issue by Wiirlak** [SoliaRdi/auto-fishing#248]
Hi, I tried to launch auto-fish with TeraToolbox but before I try to add Opcodes, it was working (wasn't requesting me 'moment') and now, here is a error on launch :

`[04:10:40.606] { Error: Cannot find module 'moment'
Require stack:
- D:\TeraToolbox\mods\auto-fishing\index.js
- D:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js
- D:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js
- D:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\index.js
- D:\TeraToolbox\node_modules\tera-network-proxy\lib\index.js
- D:\TeraToolbox\bin\connectionManager.js
- D:\TeraToolbox\bin\proxy.js
- D:\TeraToolbox\bin\loader-gui.js
- D:\TeraToolbox\bin\index-gui.js
- D:\TeraToolbox\node_modules\electron\dist\resources\default_app.asar\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (D:\TeraToolbox\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\TeraToolbox\mods\auto-fishing\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
  code: 'MODULE_NOT_FOUND',
  requireStack:
   [ 'D:\\TeraToolbox\\mods\\auto-fishing\\index.js',
     'D:\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\moduleManager.js',
     'D:\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\dispatch\\index.js',
     'D:\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\connection\\index.js',
     'D:\\TeraToolbox\\node_modules\\tera-network-proxy\\lib\\index.js',
     'D:\\TeraToolbox\\bin\\connectionManager.js',
     'D:\\TeraToolbox\\bin\\proxy.js',
     'D:\\TeraToolbox\\bin\\loader-gui.js',
     'D:\\TeraToolbox\\bin\\index-gui.js',
     'D:\\TeraToolbox\\node_modules\\electron\\dist\\resources\\default_app.asar\\main.js',
     undefined ] }`

can you help me ?

**Comment by Wiirlak** [comment]
Well, don't mind me, I find a solutioon.
node didn't want to download it in non-global... I forced it and now it works well !
