### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by sta2109** [SoliaRdi/auto-fishing#250]
[20:33:17.431] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at hook (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\mods\auto-fishing\index.js:114:18)
    at toggleHooks (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\mods\auto-fishing\index.js:126:4)
    at String.<anonymous> (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\mods\auto-fishing\index.js:1137:6)
    at CommandBase.exec (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\sta21\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:423:45)

**Comment by sta2109** [comment]
ok nvm im stupid :joy:

**Comment by Nykkyta** [comment]
I have the same issue, can you please explain how you solved it?

Cheers

**Comment by SoliaRdi** [comment]
He update opcodes

**Comment by Nykkyta** [comment]
Opcodes are the protocol.xxxxxx.map files, right? Because I also took the latest version of those files, but still doesn't work

**Comment by SoliaRdi** [comment]
What your region?

**Comment by Nykkyta** [comment]
EU

**Comment by SoliaRdi** [comment]
Then you doing smth wrong. Eu opcodes in repo

**Comment by Nykkyta** [comment]
indeed...

I started all over again, from scratch and now it works just fine.

Sorry for the trouble and thx for the answers
