### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by PHRayScott** [SoliaRdi/auto-fishing#264]
Hi Guys i dunno if this is an issue or something isnt right but it was working till this morning and now i get console error

[06:05:01.966] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\daman\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (C:\Users\daman\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\Users\daman\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (C:\Users\daman\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:114:18)
    at toggleHooks (C:\Users\daman\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:126:4)
    at String.<anonymous> (C:\Users\daman\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1136:6)
    at CommandBase.exec (C:\Users\daman\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\daman\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\daman\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\daman\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:443:45)

hope this helps Many Thanks Great Mod

**Comment by SoliaRdi** [comment]
In you on NA then sad, because i dont have full opcodes for NA yet. If on eu - update them
