### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xxbing** [SoliaRdi/auto-fishing#27]
[mods] Loaded module "Command" (command)
[mods] ERROR: Module "auto-fishing" could not be loaded!
[mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:231:23)
    at Dispatch.hook (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:310:21)
    at Module.hook (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at new autoFishing (D:\CaaliTeraProxy\mods\auto-fishing-master\index.js:32:6)
    at ModuleManager.load (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:149:35)
    at installedModules.forEach.mod (D:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach ([mods] Loaded module "badgui"
[mods] Loaded module "Bugfix" (bugfix)
[mods] Loaded module "CaaliLogger"
[mods] Loaded module "FPS-UTILS" (fps-utils)
[mods] Loaded module "InstantEverything" (instant-everything)
[mods] Loaded module "PSP" (skill-prediction)

**Comment by SoliaRdi** [comment]
no tw opcodes

**Comment by leykiyoshi** [comment]
No SEA codes as well? Not loading on my side as well

**Comment by SoliaRdi** [comment]
SEA opcodes is protocol.341702.map

**Comment by xxbing** [comment]
> no tw opcodes

thanks .
