### ISSUE TITLE
Could u pls tell me how can i fix this 

### ISSUE THREAD

**Issue by vashellsing** [SoliaRdi/auto-fishing#277]
Mybe i did something.. or this happened bc the maintenance.... 

[15:48:31.805] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:115:18)
    at toggleHooks (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:127:4)
    at String.<anonymous> (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1137:6)
    at CommandBase.exec (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\Pc\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:443:45)

**Comment by SoliaRdi** [comment]
You forgot to update opcodes

**Comment by vashellsing** [comment]
Could u pls, telle me how can i do it? D: ... (is hard?)

**Comment by SoliaRdi** [comment]
Literally top lines of readme

**Comment by vashellsing** [comment]
Ohhh, sorry for disturb..  i did it <3
