### ISSUE TITLE
Error when using new version

### ISSUE THREAD

**Issue by PiBuddy** [SoliaRdi/auto-fishing#288]
[16:54:39.927] [command] ERROR: Error: [dispatch] [auto-fishing] hook: Error: no definition found for message (name: "C_CAST_FISHING_ROD", code: 43591, version: 2)
    at Dispatch.createHook (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:247:27)
    at Dispatch.hook (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\mods\auto-fishing-master\index.js:115:18)
    at toggleHooks (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\mods\auto-fishing-master\index.js:145:5)
    at String.<anonymous> (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\mods\auto-fishing-master\index.js:1163:6)
    at CommandBase.exec (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\mods\command\index.js:196:16)
    at hookCommand (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\mods\command\index.js:71:31)
    at Object.callback (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\xxxzzz\AppData\Local\Programs\CaaliTeraProxyfish\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:443:45)

**Comment by SoliaRdi** [comment]
Maybe you forgot to restart proxy

**Comment by PiBuddy** [comment]
I restarted everything including my machine.. i will try a fresh copy of the toolbox and see if that helps.. sometimes i know mods step on each other.. i'll report back

**Comment by SoliaRdi** [comment]
This is not message when mods step on each other. Check if def still in right folder

**Comment by PiBuddy** [comment]
Something was wrong with my proxy.. it wasn't updating mods properly, so when i reinstalled from scratch, everything started working properly, including updates.
