### ISSUE TITLE
Error: [dispatch] hook: unmapped packet "S_START_FISHING_CHARGE"

### ISSUE THREAD

**Issue by LadyFire** [SoliaRdi/auto-fishing#3]
Error: [dispatch] hook: unmapped packet "S_START_FISHING_CHARGE"
    at Dispatch.createHook (C:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\c
onnection\dispatch\index.js:231:23)
    at Dispatch.hook (C:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connect
ion\dispatch\index.js:310:21)
    at Module.hook (C:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connectio
n\dispatch\module.js:87:32)
    at new autoFishing (C:\CaaliTeraProxy\mods\auto-fishing-master\index.js:31:6
)
    at ModuleManager.load (C:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\co
nnection\dispatch\moduleManager.js:138:35)
    at installedModules.forEach.mod (C:\CaaliTeraProxy\node_modules\tera-proxy-g
ame\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (C:\CaaliTeraProxy\node_modules\tera-proxy-game\li
b\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (C:\CaaliTeraProxy\node_modules\tera-p
roxy-game\lib\connection\dispatch\moduleManager.js:18:45)
    at Dispatch.emit (events.js:182:13)

**Comment by SoliaRdi** [comment]
you need na opcodes
