### ISSUE TITLE
error running callback for command "fish".

### ISSUE THREAD

**Issue by Mephistou** [SoliaRdi/auto-fishing#314]
After yesterdays EU patch. need some update pls.
(The same as was after patch before)

**Comment by PsykoDev** [comment]
S_FATIGABILITY_POINT = 24448
S_CURRENT_CHANNEL = 23563
C_CAST_FISHING_ROD = 21453
C_END_FISHING_MINIGAME = 36477
C_PUT_WARE_ITEM = 51689
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 56037
C_START_FISHING_MINIGAME = 25644
C_STOP_FISHING = 62275
C_STORE_COMMIT = 65006
C_STORE_SELL_ADD_BASKET = 58920
S_FISHING_BITE = 62833
S_FISHING_CATCH = 33271
S_CAST_FISHING_ROD = 39711
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 27219
S_START_FISHING_MINIGAME = 22386
S_STORE_BASKET = 20797
C_REQUEST_RECV_DAILY_TOKEN = 39064
S_CANT_FLY_ANYMORE = 61133
C_SELECT_CHANNEL = 49125
S_CANCEL_SELECT_CHANNEL = 63012
S_PREPARE_SELECT_CHANNEL = 42344
S_CURRENT_CHANNEL = 23563

Last EU opcode 363037

**Comment by MonoActivia** [comment]
Same error but playing in NA, a help pls : 
[02:50:14.783] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (ProxyFolder\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:236:23)
    at Dispatch.hook (ProxyFolder\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (ProxyFolder\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (ProxyFolder\TeraToolbox\mods\auto-fishing-master\index.js:115:18)
    at toggleHooks (ProxyFolder\TeraToolbox\mods\auto-fishing-master\index.js:130:4)
    at String.<anonymous> (ProxyFolder\TeraToolbox\mods\auto-fishing-master\index.js:1163:6)
    at CommandBase.exec (ProxyFolder\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (ProxyFolder\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (ProxyFolder\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (ProxyFolder\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:443:45)

**Comment by PsykoDev** [comment]
S_FATIGABILITY_POINT = 44601
S_CURRENT_CHANNEL = 60964
C_CAST_FISHING_ROD = 49903
C_END_FISHING_MINIGAME = 34898
C_PUT_WARE_ITEM = 50057
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 34198
C_START_FISHING_MINIGAME = 30849
C_STOP_FISHING = 30252
C_STORE_COMMIT = 32258
C_STORE_SELL_ADD_BASKET = 48023
S_CAST_FISHING_ROD = 54966
S_FISHING_BITE = 23762
S_FISHING_CATCH = 52483
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 35409
S_START_FISHING_MINIGAME = 60838
S_STORE_BASKET = 61509
C_REQUEST_RECV_DAILY_TOKEN = 64360
S_CANT_FLY_ANYMORE = 57490
C_SELECT_CHANNEL = 40096
S_CANCEL_SELECT_CHANNEL = 43495
S_PREPARE_SELECT_CHANNEL = 39800
S_CURRENT_CHANNEL = 60964

NA Update 88.5

**Comment by MonoActivia** [comment]
So, what should i do whit this? ´:D

**Comment by Din4EE** [comment]
Same problem with RU region

**Comment by PsykoDev** [comment]
@MonoActivia you follow this path Proxy Tera\node_modules\tera-data\map
after you edit with wordpad the good file of your version so NA protocol.359960.map 
and copy paste all inside save close all and it's good

**Comment by PsykoDev** [comment]
i don't have for RU sorry
