### ISSUE TITLE
error after toolbox update

### ISSUE THREAD

**Issue by XelZero** [SoliaRdi/auto-fishing#331]
[command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\XX\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\XX\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:283:27)
    at Module.hook (C:\Users\XX\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (C:\Users\XX\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:116:18)
    at toggleHooks (C:\Users\XX\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:131:4)
    at String.<anonymous> (C:\Users\XX\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1164:6)
    at CommandBase.exec (C:\Users\XX\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\XX\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\XX\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\XX\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:432:45)

appears they have stopped how they use the opcodes - unsure if there is a work around found or a work around that is being worked on

**Comment by SoliaRdi** [comment]
readme was updated
