### ISSUE TITLE
Error Running callback for command "fish"

### ISSUE THREAD

**Issue by bling-afk** [SoliaRdi/auto-fishing#336]
[11:17:30.695] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:283:27)
    at Module.hook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:116:18)
    at toggleHooks (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:131:4)
    at String.<anonymous> (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1164:6)
    at CommandBase.exec (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\command\index.js:201:16)
    at hookCommand (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:432:45)

this is what it says can you help please!

**Comment by bling-afk** [comment]
Tried some stuff and this is what I get now: 
[13:24:14.632] [command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:283:27)
    at Module.hook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at hook (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:116:18)
    at toggleHooks (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:131:4)
    at String.<anonymous> (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master\index.js:1164:6)
    at CommandBase.exec (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\command\index.js:201:16)
    at hookCommand (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\danie\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\danie\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:432:45)

**Comment by SoliaRdi** [comment]
This mean that you dont have opcodes. You can try to use search here to find 100+ similar issues. Anyway, this is my last comment here. Gonna archive repo. Gl to all who still playing tera ^^
