### ISSUE TITLE
autosell not work

### ISSUE THREAD

**Issue by terranceyiw** [SoliaRdi/auto-fishing#50]
![image](https://user-images.githubusercontent.com/47374421/52317022-c7a6d480-29f0-11e9-85c9-8001d3c583ce.png)

**Comment by HeliOSP** [comment]
same for me.
I've done instructions from readme

> Move defs to node_modules\tera-data\protocol.
> Move\merge protocol files to node_modules\tera-data\map in Caali proxy.

now protocol files lay here
CaaliTeraProxy\node_modules\tera-data\map\protocol.343312.map 
CaaliTeraProxy\node_modules\tera-data\map\protocol.343315.map 
CaaliTeraProxy\node_modules\tera-data\map\protocol.343317.map 
CaaliTeraProxy\node_modules\tera-data\map\protocol.343319.map

**Comment by SoliaRdi** [comment]
This mean, i doesn't have opcodes, listed in message, for your region. You have to map them yourself

**Comment by Tera-Shiraneko** [comment]
Just use opcode logger in the readme and add them yourself the protocol version can be found in node-modules/tera-data/mappings then put the opcodes if found in the right protocol file in node-modules/tera-data/map. And triggering them should be easy since the packet name already says everything you need to know.

**Comment by HeliOSP** [comment]
but these codes should work for RU
> Repo will contains opcodes only for RU
and I'm from RU
with some debugging I tried to find code with alex-packet-id-finder for C_TELEPORT_TO_VILLAGE I got code 44988 wich equal code from protocol.343317.map and I guess this is RU locale
but you have codes for missing mapping in protocol.343315.map file

also, I tried to use PacketsLogger but is throw error 
`[02:04:55.979] { Error: Cannot find module 'hexy'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (C:\Users\Sergey\AppData\Local\Programs\CaaliTeraProxy\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Sergey\AppData\Local\Programs\CaaliTeraProxy\mods\PacketsLogger-master\index.js:1:169)
    at Object.<anonymous> (C:\Users\Sergey\AppData\Local\Programs\CaaliTeraProxy\mods\PacketsLogger-master\index.js:540:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32) code: 'MODULE_NOT_FOUND' }`

**Comment by SoliaRdi** [comment]
Wait 5 min, i'll add missing on ru
