### ISSUE TITLE
How to get S_STORE_BASKET now after the patch? Also, (Tera SEA OPCODES inside)

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#82]
I already put "S_REQUEST_CONTRACT = 61940" in the opcodes. 

I cant find C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT

Also Why is it trying dismantle the fishes when I told it to sell it?

ERROR LOG:

handle: error running hook for S_REQUEST_CONTRACT<1>
hook: (anonymous) in auto-fishing
data: { senderId: ****,
  recipientId: 0n,
  type: 89,
  id: 1962434,
  unk3: 0,
  time: 0,
  senderName: '****',
  recipientName: '',
  data: <Buffer > }
error: [dispatch] write: failed to generate C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT<1>:
Error: code not known for message "C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT"
    at processDecompositionItem (D:\****\Tera SEA\CaaliTeraProxy\mods\auto-fishing-master\index.js:382:8)
    at Object.mod.hook.event [as callback] (D:\****\Tera SEA\CaaliTeraProxy\mods\auto-fishing-master\index.js:288:5)

**Comment by kath19x** [comment]
halp me >.>

**Comment by SoliaRdi** [comment]
No opcode or def for C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT.  You can log it by adding item in decomposition window

**Comment by kath19x** [comment]
I already tried it multiple times.  I can't find "C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT".  I only get S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT.  I'm using your packet logger.  Is it possible that it is black listed by default? So I have to clear the black list

**Comment by kath19x** [comment]
I used a different packetlogger and finally got the value.  This is opcodes for TERA SEA so far after the match  march 28, 2019 level 70 cap

S_FISHING_BITE = 29236
S_START_FISHING_MINIGAME = 57576
S_FISHING_CATCH = 61637
S_REQUEST_CONTRACT = 25729
C_RQ_COMMIT_DECOMPOSITION_CONTRACT = 28456
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 39925
S_FISHING_CATCH_FAIL = 26569
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46411
C_START_FISHING_MINIGAME = 58013
C_END_FISHING_MINIGAME = 50168
C_STORE_SELL_ADD_BASKET = 60107
C_STORE_COMMIT = 59186
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 53131

I'm having problems getting S_STORE_BASKET now,  If there is anyone who can help me? I know it says somewhere here the null value but the other packet logger does not seem to work now

**Comment by kath19x** [comment]
I'm still getting the S_FISHING_BITE error even though I updated all the opcodes.  Maybe the mod needs to be updated? :(

**Comment by edhe15** [comment]
@SoliaRdi  

error: S_INVEN<17>..items..customString: invalid offset for ".customString" at 521 (inside header)
    at parseField (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:414:23)
    at TeraProtocol.parse (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
    at parseField (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:384:33)
    at TeraProtocol.parse (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[17:48:41.938] [dispatch] handle: failed to parse S_INVEN<17>
hook: (anonymous) in auto-fishing

**Comment by edhe15** [comment]
Caali

error: S_INVEN<17>..items..customString: invalid offset for ".customString" at 521 (inside header)
    at parseField (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:414:23)
    at TeraProtocol.parse (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
    at parseField (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:384:33)
    at TeraProtocol.parse (E:\vv\GAME\PROXY\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[19:02:08.575] [dispatch] handle: failed to parse S_INVEN<17>
hook: (anonymous) in auto-fishing

**Comment by SoliaRdi** [comment]
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT cant be blacklisted if you don't have opcode. Name for unknown opcode would be null. You need to look packet datetime compared to your actions ingame. Server responses, hex codes, etc. S_FISHING_BITE come when you catch fish. C_START_FISHING_MINIGAME when you start minigame

**Comment by SoliaRdi** [comment]
Wait some minutes, i'll update S_INVEN

**Comment by edhe15** [comment]
@SoliaRdi Ty... No Error now.

**Comment by SoliaRdi** [comment]
I'll close it. I do not provide opcodes for SEA or guides, and you need to do it yourself. Also you can ask someone who know what he doing(not in proxy discords). For most peoples mod work fine. And i still suggest you to check with logger enabled your opcodes by manually fishing
